# Generated by Django 4.1.7 on 2023-02-27 13:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("calendar", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("artist_notes", models.TextField(blank=True, null=True)),
                ("inner_notes", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.IntegerField(
                        choices=[
                            (1, "Travel"),
                            (2, "Hotel"),
                            (3, "Other"),
                            (4, "Engagement"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "travel_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Travel to"), (2, "Travel from"), (3, "Hotel")],
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("request", "Request"),
                            ("confirmed", "Confirmed"),
                            ("contract", "Contract"),
                            ("happening", "Happening"),
                            ("inner", "Inner"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("visible_to_artist", models.BooleanField(default=False)),
                ("another_agency", models.BooleanField(default=False)),
                (
                    "engagement_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Premiere"), (2, "Performance"), (3, "Concert")],
                        null=True,
                    ),
                ),
                (
                    "travel_payment_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Per diem"),
                            (2, "Flat fee"),
                            (3, "Mileage"),
                            (4, "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "accomodation_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Hotel"), (2, "Airbnb"), (3, "Other")],
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.city",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LastSession",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "artists",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "opera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.opera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promoter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InnerFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="inner_files")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="opera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calendarik.opera",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoter",
                to="calendarik.promoter",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calendarik.role",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calendarik.promoter",
            ),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("request", "Request"),
                            ("confirmed", "Confirmed"),
                            ("contract", "Contract"),
                            ("happening", "Happening"),
                            ("inner", "Inner"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.artist",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="artist_files")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.event",
                    ),
                ),
            ],
        ),
    ]
