# Generated by Django 4.1.7 on 2023-03-03 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastsession",
            name="artists",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
