# Generated by Django 4.1.7 on 2023-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calendarik",
            "0002_event_artist_event_artist_files_event_inner_files_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="last_edited",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("request", "Request"),
                    ("confirmed", "Confirmed"),
                    ("contract", "Contract"),
                    ("happening", "Happening"),
                    ("inner", "Inner"),
                    ("normal", "Normal"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="engagement_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Premiere"), (2, "Performance"), (3, "Rehearsal")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("request", "Request"),
                    ("confirmed", "Confirmed"),
                    ("contract", "Contract"),
                    ("happening", "Happening"),
                    ("inner", "Inner"),
                    ("normal", "Normal"),
                ],
                default="normal",
                max_length=100,
                null=True,
            ),
        ),
    ]
