# Generated by Django 4.1.7 on 2023-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarik", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="period",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
