# Generated by Django 4.1.7 on 2023-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0003_event_last_edited_alter_calendarevent_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="engagement_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Premiere"), (2, "Performance"), (3, "Rehearsal")],
                null=True,
            ),
        ),
    ]
