# Generated by Django 4.1.7 on 2023-02-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendarik", "0003_calendarevent_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarik.contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoter_contact",
                to="calendarik.contact",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
