# Generated by Django 4.1.7 on 2023-03-04 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0003_remove_event_engagement_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="artist",
        ),
    ]
