# Generated by Django 4.1.7 on 2023-03-04 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0004_remove_calendarevent_artist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opera",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="opera",
            name="description",
        ),
    ]
