# Generated by Django 4.1.7 on 2023-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0004_calendarevent_engagement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="travel_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Travel to"), (2, "Travel from"), (3, "Hotel")],
                null=True,
            ),
        ),
    ]
