# Generated by Django 4.1.7 on 2023-03-02 13:34

import calendarik.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendarik", "0005_calendarevent_note_calendarevent_travel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("request", "Request"),
                            ("received", "Received"),
                            ("sent_to_artist", "Sent to artist"),
                            ("sign_by_artist", "Sign by artist"),
                            ("sent_to_promoter", "Sent to promoter"),
                            ("sign_by_promoter", "Sign by promoter"),
                            ("invoiced", "Invoiced"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarik.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET(calendarik.models.get_sentinel_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
