# Generated by Django 4.1.7 on 2023-02-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarik', '0005_alter_calendarevent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='period',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='promoter',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='role',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Travel'), (2, 'Hotel'), (3, 'Other'), (4, 'Engagement')], default=3),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoter_contact', to='calendarik.contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
