# Generated by Django 4.1.7 on 2023-02-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarik', '0006_remove_calendarevent_fee_remove_calendarevent_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarik.contact', unique_for_date='date'),
        ),
    ]
