# Generated by Django 4.1.7 on 2023-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0006_contact_notes_eventhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calendarevent",
            old_name="date",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="status",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="happend",
            field=models.BooleanField(default=False),
        ),
    ]
