# Generated by Django 4.1.7 on 2023-02-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("calendarik", "0007_alter_calendarevent_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="artist_notes",
        ),
        migrations.RemoveField(
            model_name="event",
            name="city",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="event",
            name="inner_notes",
        ),
        migrations.RemoveField(
            model_name="event",
            name="promoter",
        ),
        migrations.RemoveField(
            model_name="event",
            name="role",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="another_agency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="artist_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.city",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="event_type",
            field=models.IntegerField(
                choices=[(1, "Travel"), (2, "Hotel"), (3, "Other"), (4, "Engagement")],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="inner_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoter_contact",
                to="calendarik.contact",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="visible_to_artist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarik.contact",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarik.event",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("request", "Request"),
                    ("confirmed", "Confirmed"),
                    ("contract", "Contract"),
                    ("happening", "Happening"),
                    ("inner", "Inner"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
