# Generated by Django 4.1.7 on 2023-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0007_remove_event_accomodation_fee_currency_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventHistory",
        ),
    ]
