# Generated by Django 4.1.7 on 2023-03-10 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0009_event_conact_number_event_contract_received_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="conact_number",
            new_name="contract_number",
        ),
    ]
