# Generated by Django 4.1.7 on 2023-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarik", "0010_rename_conact_number_event_contract_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="probengeld_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
